// <auto-generated />
using ApiDicasWeb.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiDicasWeb.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221126125000_PopulandoBD")]
    partial class PopulandoBD
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ApiDicasWeb.Model.Dica", b =>
                {
                    b.Property<int>("DicaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descrição")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DicaId");

                    b.ToTable("Dicas");
                });
#pragma warning restore 612, 618
        }
    }
}
